name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11' # Use the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r djangoBackend/requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Check formatting
      run: |
        pip install black
        black --check .

    - name: Check linting
      run: |
        pip install flake8
        flake8 .
